### ISSUE TITLE
Runtime reflection is not supported for public org.apache.maven.model.Parent org.apache.maven.model.Model.getParent()

### ISSUE THREAD

**Issue by zilti** [babashka/tools.bbuild#10] opened 2023-07-26 15:48 UTC
Hi, I tried using this library to build an uberjar with Babashka. I am using `delete`, `copy-dir`, `compile-clj`, `uber`, and `create-basis` from the library. But it ends up failing instantly, before running anything, with the following error. I am using the latest commit/build.

```
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Runtime reflection is not supported for public org.apache.maven.model.Parent org.apache.maven.model.Model.getParent()
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
        at java.base@11.0.17/java.lang.reflect.Method.acquireMethodAccessor(Method.java:71)
        at java.base@11.0.17/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.plexus.interpolation.reflection.ReflectionValueExtractor.getPropertyValue(ReflectionValueExtractor.java:331)
        at org.codehaus.plexus.interpolation.reflection.ReflectionValueExtractor.evaluate(ReflectionValueExtractor.java:224)
        at org.codehaus.plexus.interpolation.ObjectBasedValueSource.getValue(ObjectBasedValueSource.java:64)
        at org.codehaus.plexus.interpolation.PrefixedValueSourceWrapper.getValue(PrefixedValueSourceWrapper.java:128)
        at org.codehaus.plexus.interpolation.AbstractDelegatingValueSource.getValue(AbstractDelegatingValueSource.java:44)
        at org.codehaus.plexus.interpolation.StringSearchInterpolator.interpolate(StringSearchInterpolator.java:200)
        at org.codehaus.plexus.interpolation.StringSearchInterpolator.interpolate(StringSearchInterpolator.java:122)
        at org.apache.maven.model.interpolation.StringVisitorModelInterpolator$1.interpolate(StringVisitorModelInterpolator.java:140)
        at org.apache.maven.model.interpolation.StringVisitorModelInterpolator$ModelVisitor.interpolate(StringVisitorModelInterpolator.java:1455)
        at org.apache.maven.model.interpolation.StringVisitorModelInterpolator$ModelVisitor.visit(StringVisitorModelInterpolator.java:1426)
        at org.apache.maven.model.interpolation.StringVisitorModelInterpolator$ModelVisitor.visit(StringVisitorModelInterpolator.java:1027)
        at org.apache.maven.model.interpolation.StringVisitorModelInterpolator$ModelVisitor.visit(StringVisitorModelInterpolator.java:170)
        at org.apache.maven.model.interpolation.StringVisitorModelInterpolator.interpolateModel(StringVisitorModelInterpolator.java:107)
        at org.apache.maven.model.building.DefaultModelBuilder.interpolateModel(DefaultModelBuilder.java:859)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:417)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:267)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:293)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:263)
        at clojure.tools.deps.extensions.maven$read_descriptor.invokeStatic(maven.clj:115)
        at clojure.tools.deps.extensions.maven$fn__805.invokeStatic(maven.clj:143)
        at clojure.tools.deps.extensions.maven$fn__805.invoke(maven.clj:143)
        at clojure.lang.MultiFn.invoke(MultiFn.java:244)
        at clojure.tools.deps$expand_deps$children_task__435$fn__437$fn__438.invoke(deps.clj:405)
        at clojure.tools.deps.util.concurrent$submit_task$task__143.invoke(concurrent.clj:35)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base@11.0.17/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base@11.0.17/java.lang.Thread.run(Thread.java:829)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

**Comment by zilti** [comment] 2023-07-26 15:53
I tracked it down a bit, it seems the issue is `create-basis`. This fails:

```clojure
(b/create-basis {:project "deps.edn" :aliases [:env/dev]})
```

**Comment by borkdude** [comment] 2023-07-26 17:07
Can you please provide the `deps.edn` because I can't reproduce this

**Comment by zilti** [comment] 2023-07-26 20:55
Sure, here:

```clojure
{:deps
 {selmer/selmer              {:mvn/version "1.12.55"}
  org.clojure/clojure        {:mvn/version "1.11.1"}
  mount/mount                {:mvn/version "0.1.16"}
  reagent/reagent            {:mvn/version "1.2.0"}
  metosin/ring-http-response {:mvn/version "0.9.2"}
  metosin/muuntaja           {:mvn/version "0.6.8"}

  kee-frame/kee-frame {:exclusions  [metosin/reitit-core org.clojure/core.async]
                       :mvn/version "1.3.2"}

  org.clojure/tools.cli                      {:mvn/version "1.0.206"}
  day8.re-frame/http-fx                      {:mvn/version "0.2.3"}
  ring/ring-defaults                         {:mvn/version "0.3.3"}
  com.cognitect/transit-cljs                 {:mvn/version "0.8.280"}
  com.cognitect/transit-clj                  {:mvn/version "1.0.333"}
  cprop/cprop                                {:mvn/version "0.1.19"}
  thheller/shadow-cljs                       {:mvn/version "2.24.0"}
  org.clojure/clojurescript                  {:mvn/version "1.11.60"}
  luminus/ring-ttl-session                   {:mvn/version "0.3.3"}
  luminus-transit/luminus-transit            {:mvn/version "0.1.2"}
  markdown-clj/markdown-clj                  {:mvn/version "1.10.5"}
  buddy/buddy-hashers                        {:mvn/version "1.8.1"}
  cljs-ajax/cljs-ajax                        {:mvn/version "0.8.3"}
  org.webjars/webjars-locator-jboss-vfs      {:mvn/version "0.1.0"}
  org.webjars/webjars-locator                {:mvn/version "0.41"}
  luminus-undertow/luminus-undertow          {:mvn/version "0.1.11"}
  nrepl/nrepl                                {:mvn/version "1.0.0"}
  clj-http/clj-http                          {:mvn/version "3.12.3"}
  expound/expound                            {:mvn/version "0.8.9"}
  metosin/reitit                             {:mvn/version "0.5.13"}
  re-frame/re-frame                          {:mvn/version "1.3.0"}
  ring/ring-core                             {:mvn/version "1.9.4"}
  org.clojure/core.async                     {:mvn/version "1.5.648"}
  com.taoensso/sente                         {:mvn/version "1.16.2"}
  clj-ocgeo/clj-ocgeo                        {:mvn/version "0.2.1"}
  com.taoensso/timbre                        {:mvn/version "5.2.1"}
  runejuhl/clj-journal                       {:mvn/version "0.3.0"}
  com.fzakaria/slf4j-timbre                  {:mvn/version "0.3.21"}
  org.postgresql/postgresql                  {:mvn/version "42.2.18"}
  optimus/optimus                            {:mvn/version "2022-02-13"}
  com.cognitect.aws/api                      {:mvn/version "0.8.539"}
  com.cognitect.aws/endpoints                {:mvn/version "1.1.12.110"}
  com.cognitect.aws/s3                       {:mvn/version "820.2.1083.0"}
  com.cognitect.aws/timestream-query         {:mvn/version "810.2.801.0"}
  com.taoensso/nippy                         {:mvn/version "3.2.0"}
  org.clj-commons/digest                     {:mvn/version "1.4.100"}
  com.xtdb/xtdb-core                         {:mvn/version "1.23.2"}
  com.xtdb/xtdb-jdbc                         {:mvn/version "1.23.2"}
  com.xtdb/xtdb-rocksdb                      {:mvn/version "1.23.2"}
  com.xtdb/xtdb-lmdb                         {:mvn/version "1.23.2"}
  com.xtdb/xtdb-s3                           {:mvn/version "1.23.2"}
  com.xtdb/xtdb-lucene                       {:mvn/version "1.23.2"}
  software.amazon.awssdk/s3-transfer-manager {:mvn/version "2.20.58"}
  software.amazon.awssdk.crt/aws-crt         {:mvn/version "0.21.14"}
  org.clojure/data.csv                       {:mvn/version "1.0.1"}
  tick/tick                                  {:mvn/version "0.6.2"}
  lambdaisland/uri                           {:mvn/version "1.15.125"}
  aysylu/loom                                {:mvn/version "1.0.2"}
  org.flatland/ordered                       {:mvn/version "1.15.11"}}
 :mvn/repos {}
 :paths     ["src/clj" "src/cljc" "src/cljs" "target/classes"
             "resources" "target/cljsbuild"]
 :aliases
 {:outdated       {:deps    {com.github.liquidz/antq {:mvn/version "2.4.1070"}}
                   :exec-fn antq.core/-main}
  :dev/deps       {:extra-deps  {binaryage/devtools          {:mvn/version "1.0.6"}
                                 pjstadig/humane-test-output {:mvn/version "0.11.0"}
                                 prone/prone                 {:mvn/version "2021-04-23"}
                                 ring/ring-devel             {:mvn/version "1.9.5"}
                                 ring/ring-mock              {:mvn/version "0.4.0"}
                                 no.cjohansen/portfolio      {:mvn/version "2023.05.12"}}
                   :extra-paths ["env/dev/clj" "env/dev/cljs" "env/dev/resources"
                                 "test/clj" "test/cljs" "portfolio"]}
  :dev/env        {:extra-deps {day8.re-frame/re-frame-10x {:mvn/version "1.5.0"}
                                day8.re-frame/tracing      {:mvn/version "0.6.2"}}
                   :jvm-opts ["-Dconf=dev-config.edn" "-Duser-start=true"]}
  :migrate        {:jvm-opts ["-Dconf=dev-config.edn"]
                   :main-opts ["-m" "redsky.core" "--migrate"]}
  :cider/clj      {:extra-deps {cider/cider-nrepl             {:mvn/version "0.30.0"}
                                refactor-nrepl/refactor-nrepl {:mvn/version "3.6.0"}}
                   :main-opts  ["-m" "nrepl.cmdline" "--middleware" "[cider.nrepl/cider-middleware]"]}
  :cider/cljs     {:extra-deps {cider/cider-nrepl             {:mvn/version "0.30.0"}
                                refactor-nrepl/refactor-nrepl {:mvn/version "3.6.0"}
                                cider/piggieback              {:mvn/version "0.5.3"}}
                   :main-opts  ["-m" "nrepl.cmdline" "--middleware"
                                "[shadow.cljs.devtools.server.nrepl/middleware,cider.piggieback/wrap-cljs-repl]"]}
  :env/prod       {:extra-paths ["env/prod/clj" "env/prod/cljs" "env/prod/resources"]}
  :env/dev        {:extra-paths ["env/dev/clj" "env/dev/cljs" "env/test/resources"]}
  :test           {:extra-deps  {lambdaisland/kaocha {:mvn/version "1.85.1342"}}
                   :extra-paths ["test/clj" "test/cljc" "test/cljs"
                                 "env/dev/clj" "env/dev/cljs"]
                   :main-opts   ["-m" "kaocha.runner"]}
  :test/refresh   {:extra-deps {com.jakemccrary/test-refresh {:mvn/version "0.25.0"}}
                   :main-opts  ["-m" "com.jakemccrary.test-refresh"]}
  :test/ci        {:jvm-opts    ["-Dconf=env/test/resources/config.edn"
                                 "-XX:+UnlockExperimentalVMOptions"
                                 "-XX:-OmitStackTraceInFastThrow"
                                 "-XX:+UseZGC"]
                   :main-opts   ["-e" "(require '[redsky.config :refer [env]] '[mount.core]) (mount.core/start)" "-m" "kaocha.runner"]
                   :extra-deps  {binaryage/devtools          {:mvn/version "1.0.6"}
                                 pjstadig/humane-test-output {:mvn/version "0.11.0"}
                                 prone/prone                 {:mvn/version "2021-04-23"}
                                 ring/ring-devel             {:mvn/version "1.9.5"}
                                 ring/ring-mock              {:mvn/version "0.4.0"}}
                   :extra-paths ["env/test/resources" "target/cljsbuild"]}
  :uberjar/build  {:deps        {io.github.clojure/tools.build {:mvn/version "0.9.4"}}
                   :extra-paths ["."]}
  :cljfmt         {:deps       {io.github.weavejester/cljfmt {:git/tag "0.10.5"
                                                              :git/sha "e19a304"}}
                   :main-opts  [":paths" "[\"src\"]"]
                   :ns-default cljfmt.tool}
  :run            {:exec-fn user/start}}}
```

**Comment by borkdude** [comment] 2023-07-27 10:05
I can repro with your deps.edn, thanks.
<img width="1483" alt="Screenshot 2023-07-27 at 12 04 50" src="https://github.com/babashka/tools.bbuild/assets/284934/ac16542d-833b-4358-9872-ea31cc5c34d8">

**Comment by borkdude** [comment] 2023-07-27 10:37
I pushed a fix to tools-deps-native that fixes some reflection issues. It now works when I remove the s3 deps:

```
  #_#_com.xtdb/xtdb-s3                           {:mvn/version "1.23.2"}
  com.xtdb/xtdb-lucene                       {:mvn/version "1.23.2"}
  #_#_#_#_software.amazon.awssdk/s3-transfer-manager {:mvn/version "2.20.58"}
  software.amazon.awssdk.crt/aws-crt         {:mvn/version "0.21.14"}
```

I'm getting:

```
clojure.lang.ExceptionInfo: Failed to read artifact descriptor for software.amazon.awssdk:s3-transfer-manager:jar:2.19.21 [at /Users/borkdude/dev/tools.bbuild/src/main/clojure/clojure/tools/build/util/pod.clj:1:29]
```

for those. Not sure what the problem is with that dependency, need to look into it.

**Comment by borkdude** [comment] 2023-07-27 11:11
Ah, found it.

**Comment by zilti** [comment] 2023-07-27 11:41
Ah so those are to blame! Okay, thanks a lot for the very quick fix!

**Comment by zilti** [comment] 2023-07-27 11:50
What is/was it with the s3 dependencies? And do I have to do something special to make tools.bbuild use the newest snapshot of tools-deps-native?

**Comment by borkdude** [comment] 2023-07-27 11:51
To test you can download the binary file for your OS from tools-deps-native and put it in your local project directory

**Comment by borkdude** [comment] 2023-07-27 12:04
I'm going to release the pod v0.1.1 now. I've added a test with your deps. Soon after, I'll update this project.

**Comment by borkdude** [comment] 2023-07-27 12:45
Should be fixed with https://github.com/babashka/tools.bbuild/commit/73e4d0a26c65cdf1d4c7bf7e9e46e6e5f1978a37
Can you test?

**Closed as completed** 2023-07-27 13:41 UTC

**Comment by zilti** [comment] 2023-07-27 14:28
Yes, I can confirm it works perfectly now!
